apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-template
  namespace: cesieats-frontend
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: react-template
  template:
    metadata:
      labels:
        app: react-template
    spec:
      containers:
        - name: react-template
          image: kilme/react-template:$IMAGE_VERSION
          env:
          - name: DB_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: mongodb-credentials
                key: username
          - name: DB_URL
            valueFrom: 
              configMapKeyRef:
                name: mongodb-credentials
                key: services-url
          - name: DB_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: mongodb-credentials-secret
                key: password
          - name: RABBITMQ_USERNAME
            valueFrom: 
              configMapKeyRef:
                name: rabbitmq-credentials
                key: username
          - name: RABBITMQ_URL
            valueFrom: 
              configMapKeyRef:
                name: rabbitmq-credentials
                key: services-url
          - name: RABBITMQ_PASSWORD
            valueFrom: 
              secretKeyRef:
                name: rabbitmq-credentials-secret
                key: password
          - name: JWT_KEY
            valueFrom: 
              secretKeyRef:
                name: default-credentials-secret
                key: jwt-key
          - name: BASE64_KEY
            valueFrom: 
              secretKeyRef:
                name: default-credentials-secret
                key: base64-key
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: service-react-template
  namespace: cesieats-frontend
spec:
  selector:
    app: react-template
  ports:
    - name: http
      protocol: TCP
      port: 3000
      nodePort: 30101
  type: NodePort